//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3.LectorsSeminarsDataAccessLayerWCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdNamable", Namespace="http://schemas.datacontract.org/2004/07/LectorsSeminarsDataAccessLayer")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(T3.LectorsSeminarsDataAccessLayerWCFService.Seminar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(T3.LectorsSeminarsDataAccessLayerWCFService.Lector))]
    public partial class IdNamable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seminar", Namespace="http://schemas.datacontract.org/2004/07/LectorsSeminarsDataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Seminar : T3.LectorsSeminarsDataAccessLayerWCFService.IdNamable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Lector> LectorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Lector> Lectors {
            get {
                return this.LectorsField;
            }
            set {
                if ((object.ReferenceEquals(this.LectorsField, value) != true)) {
                    this.LectorsField = value;
                    this.RaisePropertyChanged("Lectors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lector", Namespace="http://schemas.datacontract.org/2004/07/LectorsSeminarsDataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Lector : T3.LectorsSeminarsDataAccessLayerWCFService.IdNamable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Seminar> SeminarsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthdayField, value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Seminar> Seminars {
            get {
                return this.SeminarsField;
            }
            set {
                if ((object.ReferenceEquals(this.SeminarsField, value) != true)) {
                    this.SeminarsField = value;
                    this.RaisePropertyChanged("Seminars");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LectorsSeminarsDataAccessLayerWCFService.ILectorsSeminarsDataAccessLayerService")]
    public interface ILectorsSeminarsDataAccessLayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetLectorById", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetLectorByIdResponse")]
        T3.LectorsSeminarsDataAccessLayerWCFService.Lector GetLectorById(string sessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetLectorById", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetLectorByIdResponse")]
        System.Threading.Tasks.Task<T3.LectorsSeminarsDataAccessLayerWCFService.Lector> GetLectorByIdAsync(string sessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetAllLectors", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetAllLectorsResponse")]
        System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Lector> GetAllLectors(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetAllLectors", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetAllLectorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Lector>> GetAllLectorsAsync(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetSeminarById", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetSeminarByIdResponse")]
        T3.LectorsSeminarsDataAccessLayerWCFService.Seminar GetSeminarById(string sessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetSeminarById", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetSeminarByIdResponse")]
        System.Threading.Tasks.Task<T3.LectorsSeminarsDataAccessLayerWCFService.Seminar> GetSeminarByIdAsync(string sessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetAllSeminars", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetAllSeminarsResponse")]
        System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Seminar> GetAllSeminars(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetAllSeminars", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GetAllSeminarsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Seminar>> GetAllSeminarsAsync(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/SaveObject", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/SaveObjectResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(T3.LectorsSeminarsDataAccessLayerWCFService.Lector))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(T3.LectorsSeminarsDataAccessLayerWCFService.IdNamable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Seminar>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(T3.LectorsSeminarsDataAccessLayerWCFService.Seminar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Lector>))]
        void SaveObject(string sessionKey, object obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/SaveObject", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/SaveObjectResponse")]
        System.Threading.Tasks.Task SaveObjectAsync(string sessionKey, object obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/DeleteObject", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/DeleteObjectResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(T3.LectorsSeminarsDataAccessLayerWCFService.Lector))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(T3.LectorsSeminarsDataAccessLayerWCFService.IdNamable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Seminar>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(T3.LectorsSeminarsDataAccessLayerWCFService.Seminar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Lector>))]
        void DeleteObject(string sessionKey, object obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/DeleteObject", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/DeleteObjectResponse")]
        System.Threading.Tasks.Task DeleteObjectAsync(string sessionKey, object obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/CloseSession", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/CloseSessionResponse")]
        void CloseSession(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/CloseSession", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/CloseSessionResponse")]
        System.Threading.Tasks.Task CloseSessionAsync(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/DoWork", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/DoWorkResponse")]
        string DoWork(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/DoWork", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GenerateSession", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GenerateSessionResponse" +
            "")]
        string GenerateSession();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GenerateSession", ReplyAction="http://tempuri.org/ILectorsSeminarsDataAccessLayerService/GenerateSessionResponse" +
            "")]
        System.Threading.Tasks.Task<string> GenerateSessionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILectorsSeminarsDataAccessLayerServiceChannel : T3.LectorsSeminarsDataAccessLayerWCFService.ILectorsSeminarsDataAccessLayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LectorsSeminarsDataAccessLayerServiceClient : System.ServiceModel.ClientBase<T3.LectorsSeminarsDataAccessLayerWCFService.ILectorsSeminarsDataAccessLayerService>, T3.LectorsSeminarsDataAccessLayerWCFService.ILectorsSeminarsDataAccessLayerService {
        
        public LectorsSeminarsDataAccessLayerServiceClient() {
        }
        
        public LectorsSeminarsDataAccessLayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LectorsSeminarsDataAccessLayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LectorsSeminarsDataAccessLayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LectorsSeminarsDataAccessLayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public T3.LectorsSeminarsDataAccessLayerWCFService.Lector GetLectorById(string sessionKey, int Id) {
            return base.Channel.GetLectorById(sessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<T3.LectorsSeminarsDataAccessLayerWCFService.Lector> GetLectorByIdAsync(string sessionKey, int Id) {
            return base.Channel.GetLectorByIdAsync(sessionKey, Id);
        }
        
        public System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Lector> GetAllLectors(string sessionKey) {
            return base.Channel.GetAllLectors(sessionKey);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Lector>> GetAllLectorsAsync(string sessionKey) {
            return base.Channel.GetAllLectorsAsync(sessionKey);
        }
        
        public T3.LectorsSeminarsDataAccessLayerWCFService.Seminar GetSeminarById(string sessionKey, int Id) {
            return base.Channel.GetSeminarById(sessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<T3.LectorsSeminarsDataAccessLayerWCFService.Seminar> GetSeminarByIdAsync(string sessionKey, int Id) {
            return base.Channel.GetSeminarByIdAsync(sessionKey, Id);
        }
        
        public System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Seminar> GetAllSeminars(string sessionKey) {
            return base.Channel.GetAllSeminars(sessionKey);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<T3.LectorsSeminarsDataAccessLayerWCFService.Seminar>> GetAllSeminarsAsync(string sessionKey) {
            return base.Channel.GetAllSeminarsAsync(sessionKey);
        }
        
        public void SaveObject(string sessionKey, object obj) {
            base.Channel.SaveObject(sessionKey, obj);
        }
        
        public System.Threading.Tasks.Task SaveObjectAsync(string sessionKey, object obj) {
            return base.Channel.SaveObjectAsync(sessionKey, obj);
        }
        
        public void DeleteObject(string sessionKey, object obj) {
            base.Channel.DeleteObject(sessionKey, obj);
        }
        
        public System.Threading.Tasks.Task DeleteObjectAsync(string sessionKey, object obj) {
            return base.Channel.DeleteObjectAsync(sessionKey, obj);
        }
        
        public void CloseSession(string sessionKey) {
            base.Channel.CloseSession(sessionKey);
        }
        
        public System.Threading.Tasks.Task CloseSessionAsync(string sessionKey) {
            return base.Channel.CloseSessionAsync(sessionKey);
        }
        
        public string DoWork(string name) {
            return base.Channel.DoWork(name);
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync(string name) {
            return base.Channel.DoWorkAsync(name);
        }
        
        public string GenerateSession() {
            return base.Channel.GenerateSession();
        }
        
        public System.Threading.Tasks.Task<string> GenerateSessionAsync() {
            return base.Channel.GenerateSessionAsync();
        }
    }
}
