//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3.LectorsSeminarsNamespace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LectorsSeminarsNamespace.ILectorsSeminarsService")]
    public interface ILectorsSeminarsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsService/GetLectors", ReplyAction="http://tempuri.org/ILectorsSeminarsService/GetLectorsResponse")]
        LectorsSeminarsDataAccessLayer.Lector[] GetLectors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsService/GetLectors", ReplyAction="http://tempuri.org/ILectorsSeminarsService/GetLectorsResponse")]
        System.Threading.Tasks.Task<LectorsSeminarsDataAccessLayer.Lector[]> GetLectorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsService/GetSeminars", ReplyAction="http://tempuri.org/ILectorsSeminarsService/GetSeminarsResponse")]
        LectorsSeminarsDataAccessLayer.Seminar[] GetSeminars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectorsSeminarsService/GetSeminars", ReplyAction="http://tempuri.org/ILectorsSeminarsService/GetSeminarsResponse")]
        System.Threading.Tasks.Task<LectorsSeminarsDataAccessLayer.Seminar[]> GetSeminarsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILectorsSeminarsServiceChannel : T3.LectorsSeminarsNamespace.ILectorsSeminarsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LectorsSeminarsServiceClient : System.ServiceModel.ClientBase<T3.LectorsSeminarsNamespace.ILectorsSeminarsService>, T3.LectorsSeminarsNamespace.ILectorsSeminarsService {
        
        public LectorsSeminarsServiceClient() {
        }
        
        public LectorsSeminarsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LectorsSeminarsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LectorsSeminarsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LectorsSeminarsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LectorsSeminarsDataAccessLayer.Lector[] GetLectors() {
            return base.Channel.GetLectors();
        }
        
        public System.Threading.Tasks.Task<LectorsSeminarsDataAccessLayer.Lector[]> GetLectorsAsync() {
            return base.Channel.GetLectorsAsync();
        }
        
        public LectorsSeminarsDataAccessLayer.Seminar[] GetSeminars() {
            return base.Channel.GetSeminars();
        }
        
        public System.Threading.Tasks.Task<LectorsSeminarsDataAccessLayer.Seminar[]> GetSeminarsAsync() {
            return base.Channel.GetSeminarsAsync();
        }
    }
}
